### ISSUE TITLE
Wrong Array index?

### ISSUE THREAD

**Issue by MattMcGregor99** [lushaylabs/tangnano9k-series-examples#1]
https://github.com/lushaylabs/tangnano9k-series-examples/blob/a8c6281bb20f62bc0b2fa152d756e99d1082fdce/uart/uart.v#L102

I think
testMemory[10] = " ";

should be
testMemory[11] = " ";

**Comment by lushaylabs** [comment]
You are right, will update it now

**Comment by lushaylabs** [comment]
Has been updated, thank you for pointing this out
