### ISSUE TITLE
Problem with UART - no tty device detected

### ISSUE THREAD

**Issue by fedor-goncharov** [lushaylabs/tangnano9k-series-examples#14]
Hi, I did the tutorial on UART on my Tang Nano 9k, flashed with no errors but I struggle to communicate with 
board via UART: 

```OS : ubuntu 23.10```

my dmesg on plug-in
```
[28637.616311] usb 1-2: New USB device found, idVendor=0403, idProduct=6010, bcdDevice= 5.00
[28637.616320] usb 1-2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[28637.616323] usb 1-2: Product: JTAG Debugger
[28637.616325] usb 1-2: Manufacturer: SIPEED
[28637.616327] usb 1-2: SerialNumber: FactoryAIOT Pro
```

lsusb 
```Bus 001 Device 008: ID 0403:6010 Future Technology Devices International, Ltd FT2232C/D/H Dual UART/FIFO IC```
and -v option gives 

```
Bus 001 Device 013: ID 0403:6010 Future Technology Devices International, Ltd FT2232C/D/H Dual UART/FIFO IC
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 [unknown]
  bDeviceSubClass         0 [unknown]
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x0403 Future Technology Devices International, Ltd
  idProduct          0x6010 FT2232C/D/H Dual UART/FIFO IC
  bcdDevice            5.00
  iManufacturer           1 SIPEED
  iProduct                2 JTAG Debugger
  iSerial                 3 FactoryAIOT Pro
  bNumConfigurations      1

 Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0037
    bNumInterfaces          2
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower               90mA
   .... 
```
it is important 2 interfaces!

For fun ```openFPGALoader --detect``` (I think before it was showing two devices and noticed that 
one was UART and the other was JTAG):

```No cable or board specified: using direct ft2232 interface
Jtag frequency : requested 6.00MHz   -> real 6.00MHz  
index 0:
	idcode 0x100481b
	manufacturer Gowin
	family GW1N
	model  GW1N(R)-9C
	irlength 8
```

**Comment by fedor-goncharov** [comment]
To add : I use recommended version of OSS tools, native Gowin Programmer tool detects two "cables" (as far as I understand, "cables" correspond to devices in Linux) -> one cable allows to do all memory resets when I need (I guess it
is a JTAG interface) and the other throws "Cable open failed"

**Comment by fedor-goncharov** [comment]
I understood that issue is not related to the board nor to the the oss-cad-suite but to FTDI kernel module in Ubuntu. 

The tty device appeared after I loaded kernel module to support FTDI devices : 
``` sudo modprobe ftdi_sio```
Then I could connect serially to the board via UART (e.g., as in tutorials), however, kernel still recieves 
some errors when working with the board. I wonder actually if the board is simply have a damaged USB port. 

@lushaylabs Maybe it is worth to put this solution to put it somewhere in tutorials / FAQ for Linux users

P. S. I still experience lots of problems to load stuff to Tang Nano 9k under Ubuntu - constant CRC errors 
(seems to be Apicula issue https://github.com/YosysHQ/apicula/issues/262 which should be 
fixed by now but OSS cad suite then should be updated) and sometimes FTDI kernel module crashes when I flash the board (both RAM and embedded flash). 

It is really annoying, that I have to re-flash the board ~20 times before 
it succeeds without errors (no CRC problem, no FTDI module crash).

**Comment by lushaylabs** [comment]
Hey @fedor-goncharov thank you for reaching out and sorry for the slow reply,  just to check did you try testing the fs file from [here](https://github.com/lushaylabs/tangnano9k-series-examples/blob/master/counter/counter.fs) as-is, it uses an older version of OSS-CAD-Suite before the CRC issue so it would be interesting to see if it works.

I saw you were having some trouble erasing the flash all of a sudden on the tang nano 9k, if you can send me an email (contact@lushaylabs.com) I will try debug it with you there

I also haven't tested Ubuntu 23, so I will give that a try over the weekend and update the docs accordingly once we get this working.
